import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, Tab, TextField, Typography } from '@mui/material';
import api from '../../services/api';
import MemberAttendanceSection from '../../components/church/MemberAttendanceSection';
import PrintDocument from '../../components/common/PrintDocument';
import { attendanceDateRange, defaultAttendanceRange } from '../../lib/memberAttendance';
const name = (m: any) => `${m.firstName || ''} ${m.lastName || ''}`.trim();
const failure = (e: any) => e?.response?.data?.error || 'Could not complete the request. Please retry.';
export default function GroupLeaderPortal() {
  const [groups, setGroups] = useState<any[]>([]), [groupId, setGroupId] = useState(''), [data, setData] = useState<any>(null);
  const [range, setRange] = useState(defaultAttendanceRange), [draft, setDraft] = useState(defaultAttendanceRange);
  const [tab, setTab] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(''), [revision, setRevision] = useState(0);
  const [selected, setSelected] = useState<any>(null), [search, setSearch] = useState(''), [print, setPrint] = useState(false), [care, setCare] = useState(false), [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ memberId: '', type: 'call', note: '', dueAt: '' });
  useEffect(() => { let active = true; setLoading(true); api.get('/group-leader/groups').then(r => { if (!active) return; setGroups(r.data.data); setGroupId(current => r.data.data.some((g: any) => g.id === current) ? current : r.data.data[0]?.id || ''); if (!r.data.data.length) setLoading(false); }).catch(e => { if (active) { setError(failure(e)); setLoading(false); } }); return () => { active = false; }; }, [revision]);
  useEffect(() => { setSelected(null); if (!groupId) return; const controller = new AbortController(); setData(null); setLoading(true); setError(''); api.get(`/group-leader/groups/${encodeURIComponent(groupId)}/overview`, { params: range, signal: controller.signal }).then(r => { if (!controller.signal.aborted) setData(r.data); }).catch(e => { if (!controller.signal.aborted) setError(failure(e)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [groupId, range, revision]);
  const loadAttendance = useCallback(async (memberId: string, dates: any, signal?: AbortSignal) => (await api.get(`/group-leader/groups/${encodeURIComponent(groupId)}/members/${encodeURIComponent(memberId)}/attendance`, { params: dates, signal })).data, [groupId]);
  const apply = () => { try { attendanceDateRange(draft.from, draft.to); setError(''); setRange({ ...draft }); } catch (e: any) { setError(e.message); } };
  const save = async () => { setSaving(true); setError(''); try { await api.post(`/group-leader/groups/${encodeURIComponent(groupId)}/followups`, { ...form, dueAt: form.dueAt ? new Date(form.dueAt).toISOString() : null }); setCare(false); setRevision(v => v + 1); } catch (e) { setError(failure(e)); } finally { setSaving(false); } };
  const changeStatus = async (f: any) => { setSaving(true); try { await api.patch(`/group-leader/groups/${encodeURIComponent(groupId)}/followups/${encodeURIComponent(f.id)}`, { status: f.status === 'open' ? 'completed' : 'open' }); setRevision(v => v + 1); } catch (e) { setError(failure(e)); } finally { setSaving(false); } };
  const members = data?.members || [], filtered = members.filter((m: any) => `${name(m)} ${m.membershipId}`.toLowerCase().includes(search.toLowerCase()));
  const open = (data?.followups || []).filter((f: any) => f.status === 'open').length;
  const marked = members.reduce((s: number, m: any) => s + m.attendance.marked, 0), present = members.reduce((s: number, m: any) => s + m.attendance.present, 0);
  const roster = <Table size="small"><TableHead><TableRow>{['Member', 'Member ID', 'Present', 'Absent', 'Attendance rate'].map(c => <TableCell key={c}>{c}</TableCell>)}</TableRow></TableHead><TableBody>{filtered.map((m: any) => <TableRow key={m.id}><TableCell>{name(m)}</TableCell><TableCell>{m.membershipId}</TableCell><TableCell>{m.attendance.present}</TableCell><TableCell>{m.attendance.absent}</TableCell><TableCell>{m.attendance.rate == null ? 'Not marked' : `${m.attendance.rate}%`}</TableCell></TableRow>)}</TableBody></Table>;
  return <Stack spacing={3}>
    <Box><Typography variant="h4" fontWeight={800}>Care for your group</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Stay connected, review attendance and follow up with the people entrusted to you.</Typography></Box>
    {error && <Alert severity="error" action={<Button onClick={() => setRevision(v => v + 1)}>Retry</Button>}>{error}</Alert>}
    {groups.length > 0 && <Stack direction={{ xs: 'column', md: 'row' }} gap={2} alignItems={{ md: 'center' }}>
      <TextField select label="Assigned group" value={groupId} onChange={e => setGroupId(e.target.value)} sx={{ minWidth: 220 }}>{groups.map(g => <MenuItem key={g.id} value={g.id}>{g.name}</MenuItem>)}</TextField>
      <TextField type="date" label="From (UTC)" value={draft.from} onChange={e => setDraft(v => ({ ...v, from: e.target.value }))} slotProps={{ inputLabel: { shrink: true } }} />
      <TextField type="date" label="To (UTC)" value={draft.to} onChange={e => setDraft(v => ({ ...v, to: e.target.value }))} slotProps={{ inputLabel: { shrink: true } }} /><Button variant="contained" onClick={apply}>Apply range</Button>
    </Stack>}
    {loading ? <Box sx={{ p: 4, textAlign: 'center' }}><CircularProgress aria-label="Loading assigned group" /></Box> : !groups.length ? <Alert severity="info">No active group is assigned to your account. Ask your church administrator to assign you under Settings → Groups.</Alert> : data && <>
      <Card variant="outlined"><CardContent><Typography variant="h6" fontWeight={700}>{data.group.name}</Typography><Typography color="text.secondary">{data.group.description || 'Your group members and care activity.'}</Typography><Typography sx={{ mt: 1 }}>{data.group.meetingDays?.join(', ') || 'Meeting days not set'}{data.group.meetingTime ? ` · ${data.group.meetingTime}` : ''}{data.group.location ? ` · ${data.group.location}` : ''}</Typography></CardContent></Card>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2, minmax(0, 1fr))', md: 'repeat(4, minmax(0, 1fr))' }, gap: 2 }}>{[['Group members', members.length], ['Recorded attendance', marked ? `${Math.round(present / marked * 100)}%` : 'Not marked'], ['Open follow-ups', open], ['Members with absence marks', members.filter((m: any) => m.attendance.absent > 0).length]].map(([label, value]) => <Card variant="outlined" key={String(label)}><CardContent><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="h5" fontWeight={800}>{value}</Typography></CardContent></Card>)}</Box>
      <Typography variant="body2" color="text.secondary">{range.from} – {range.to}, inclusive UTC event dates. Registrations and unmarked events are not counted as absences.</Typography>
      <Tabs value={tab} onChange={(_, v) => setTab(v)} variant="scrollable" scrollButtons="auto"><Tab label="Members & contacts" /><Tab label="Attendance report" /><Tab label="Follow-up care" /></Tabs>
      {tab === 0 && <><TextField label="Find a group member" value={search} onChange={e => setSearch(e.target.value)} /><Stack spacing={1}>{filtered.map((m: any) => <Card variant="outlined" key={m.id}><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1}><Box><Typography fontWeight={700}>{name(m)}</Typography><Typography variant="body2" color="text.secondary">{m.membershipId} · {m.membershipStatus || 'Member'}</Typography><Typography variant="body2">{m.phone || 'No phone'} · {m.email || 'No email'}</Typography></Box><Stack direction="row" gap={1} flexWrap="wrap"><Button onClick={() => setSelected(m)}>Attendance</Button><Button onClick={() => { setForm({ memberId: m.id, type: 'call', note: '', dueAt: '' }); setCare(true); }}>Add follow-up</Button></Stack></Stack></CardContent></Card>)}{!filtered.length && <Alert severity="info">No matching group members.</Alert>}</Stack></>}
      {tab === 1 && <><Stack direction={{ xs: 'column', sm: 'row' }} gap={2}><TextField label="Filter members" value={search} onChange={e => setSearch(e.target.value)} /><Button variant="outlined" onClick={() => setPrint(true)}>Print attendance report</Button></Stack><TableContainer sx={{ border: 1, borderColor: 'divider', borderRadius: 1 }}>{roster}</TableContainer></>}
      {tab === 2 && <><Alert severity="info">Record practical care actions, not confidential counseling, medical details or financial information. Notes are visible to the group's currently assigned leader and authorized church administrators.</Alert><Button variant="contained" disabled={!members.length} onClick={() => { setForm({ memberId: members[0]?.id || '', type: 'call', note: '', dueAt: '' }); setCare(true); }}>New follow-up</Button>{(data.followups || []).map((f: any) => <Card variant="outlined" key={f.id}><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography fontWeight={700}>{name(members.find((m: any) => m.id === f.memberId) || {})} · {f.type}</Typography><Typography sx={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', my: 1 }}>{f.note}</Typography><Typography variant="body2" color="text.secondary">{f.dueAt ? `Due ${new Date(f.dueAt).toLocaleString()}` : 'No due date'} · Logged {new Date(f.createdAt).toLocaleString()}</Typography></Box><Stack gap={1}><Chip label={f.status} color={f.status === 'completed' ? 'success' : 'default'} /><Button disabled={saving} onClick={() => changeStatus(f)}>{f.status === 'open' ? 'Mark completed' : 'Reopen'}</Button></Stack></Stack></CardContent></Card>)}{!data.followups.length && <Typography color="text.secondary">No care actions recorded yet.</Typography>}</>}
    </>}
    <Dialog open={!!selected} onClose={() => setSelected(null)} fullWidth maxWidth="md"><DialogTitle>{selected ? `${name(selected)} · attendance` : 'Attendance'}</DialogTitle><DialogContent>{selected && <MemberAttendanceSection memberId={selected.id} loadAttendance={loadAttendance} />}</DialogContent><DialogActions><Button onClick={() => setSelected(null)}>Close</Button></DialogActions></Dialog>
    <Dialog open={care} onClose={() => { if (!saving) setCare(false); }} fullWidth><DialogTitle>Plan a follow-up</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField select label="Group member" value={form.memberId} onChange={e => setForm(v => ({ ...v, memberId: e.target.value }))}>{members.map((m: any) => <MenuItem key={m.id} value={m.id}>{name(m)}</MenuItem>)}</TextField><TextField select label="Care type" value={form.type} onChange={e => setForm(v => ({ ...v, type: e.target.value }))}>{['call', 'visit', 'check-in', 'prayer', 'other'].map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField><TextField label="Care note" multiline minRows={3} value={form.note} onChange={e => setForm(v => ({ ...v, note: e.target.value }))} slotProps={{ htmlInput: { maxLength: 2000 } }} /><TextField type="datetime-local" label="Follow-up due" value={form.dueAt} onChange={e => setForm(v => ({ ...v, dueAt: e.target.value }))} slotProps={{ inputLabel: { shrink: true } }} />{error && <Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions><Button disabled={saving} onClick={() => setCare(false)}>Cancel</Button><Button disabled={saving || !form.memberId || !form.note.trim()} variant="contained" onClick={save}>{saving ? 'Saving…' : 'Save follow-up'}</Button></DialogActions></Dialog>
    {print && <PrintDocument title={`${data?.group.name} · attendance report`} onClose={() => setPrint(false)}><Typography sx={{ mb: 2 }}>{range.from} – {range.to} · UTC event dates · Recorded marks only{search ? ` · Filter: ${search}` : ''}</Typography>{roster}</PrintDocument>}
  </Stack>;
}
