import React, { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, CircularProgress, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import api from '../../services/api';
import CrudTable from '../../components/church/CrudTable';
import PrintDocument from '../../components/common/PrintDocument';
import { financeRange } from '../../lib/financeReports';
const money = (n: any, currency = 'GHS') => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(Number(n) || 0);
const stamp = (d: any) => d ? new Date(d).toLocaleString(undefined, { timeZone: 'UTC' }) + ' UTC' : '—';
const today = () => new Date().toISOString().slice(0, 10);
const defaultRange = () => ({ from: `${today().slice(0, 7)}-01`, to: today(), horizon: 3 });
const problem = (e: any) => e?.response?.data?.error || 'Could not load financial records. Please retry.';
type Column = { title: string; value: (r: any) => React.ReactNode };
function Records({ rows, columns }: { rows: any[]; columns: Column[] }) {
  return <TableContainer className="document-table"><Table size="small"><TableHead><TableRow>{columns.map(c => <TableCell key={c.title}>{c.title}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map((r, i) => <TableRow key={r.id || i}>{columns.map(c => <TableCell key={c.title}>{c.value(r)}</TableCell>)}</TableRow>)}{!rows.length && <TableRow><TableCell colSpan={columns.length}>No records in this document.</TableCell></TableRow>}</TableBody></Table></TableContainer>;
}
export default function FinanceDocuments() {
  const [range, setRange] = useState(defaultRange), [draft, setDraft] = useState(defaultRange);
  const [data, setData] = useState<any>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [revision, setRevision] = useState(0);
  const [currency, setCurrency] = useState('all'), [documentType, setDocumentType] = useState('statement'), [recordId, setRecordId] = useState(''), [print, setPrint] = useState(false);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); setData(null); api.get('/church/finance/report', { params: range, signal: controller.signal }).then(r => { if (!controller.signal.aborted) { setData(r.data); setRecordId(''); } }).catch(e => { if (!controller.signal.aborted) setError(problem(e)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [range, revision]);
  const apply = () => { try { financeRange(draft.from, draft.to); setRange({ ...draft }); setError(''); } catch (e: any) { setError(e.message); } };
  const currencies: string[] = [...new Set<string>([...(data?.totals || []).map((t: any) => t.currency), ...(data?.invoices || []).map((r: any) => r.currency || 'GHS')])];
  const inCurrency = (r: any) => currency === 'all' || (r.currency || 'GHS') === currency;
  const totals = (data?.totals || []).filter(inCurrency), giving = (data?.giving || []).filter(inCurrency), expenses = (data?.expenses || []).filter(inCurrency), invoices = (data?.invoices || []).filter(inCurrency);
  const receiptOptions = giving.filter((g: any) => g.status === 'completed');
  const individualRows = documentType === 'receipt' ? receiptOptions : documentType === 'invoice' ? invoices : [];
  const selected = individualRows.find((r: any) => String(r.id) === recordId);
  const types = [['statement', 'Income & expenditure statement'], ['tithes', 'Tithe collection report'], ['receipt', 'Giving receipt'], ['invoice', 'Church invoice'], ['expenses', 'Expense vouchers / register'], ['forecast', 'Financial forecast'], ['budgets', 'Budget snapshot'], ['pledges', 'Pledge snapshot']];
  const columns: Column[] = [ { title: 'Collection time', value: r => stamp(r.receivedAt) }, { title: 'Giver', value: r => r.donorName || 'Anonymous' }, { title: 'Purpose', value: r => r.purpose || 'General' }, { title: 'Amount', value: r => money(r.amount, r.currency) }, { title: 'Status', value: r => r.status }, { title: 'Recorded at', value: r => stamp(r.createdAt) } ];
  const expenseColumns: Column[] = [ { title: 'Expense time', value: r => stamp(r.date) }, { title: 'Payee', value: r => r.vendor || '—' }, { title: 'Description', value: r => r.description || r.category }, { title: 'Amount', value: r => money(r.amount, r.currency) }, { title: 'Status', value: r => r.status }, { title: 'Recorded at', value: r => stamp(r.createdAt) } ];
  const documentBody = <Stack spacing={3}>
    <Box><Typography variant="h6" fontWeight={700}>{data?.churchName}</Typography><Typography>{data?.from} – {data?.to} · Inclusive UTC calendar days</Typography><Typography variant="body2" color="text.secondary">Generated {stamp(data?.generatedAt)} · {currency === 'all' ? 'Currencies reported separately' : currency}</Typography></Box>
    {['statement', 'tithes', 'forecast'].includes(documentType) && <Records rows={totals} columns={documentType === 'forecast' ? [ { title: 'Currency', value: r => r.currency }, { title: `Projected income (${range.horizon} months)`, value: r => money(r.projectedIncome, r.currency) }, { title: 'Projected paid expenses', value: r => money(r.projectedExpenses, r.currency) }, { title: 'Projected net cash', value: r => money(r.projectedNet, r.currency) } ] : documentType === 'tithes' ? [ { title: 'Currency', value: r => r.currency }, { title: 'Completed tithes', value: r => money(r.tithes, r.currency) } ] : [ { title: 'Currency', value: r => r.currency }, { title: 'Completed income', value: r => money(r.income, r.currency) }, { title: 'Paid expenses', value: r => money(r.expenses, r.currency) }, { title: 'Net movement', value: r => money(r.net, r.currency) } ]} />}
    {documentType === 'forecast' && <Alert severity="info">{data?.forecastMethod} Missing or unrecorded transactions may make this estimate unreliable.</Alert>}
    {documentType === 'statement' && <><Typography variant="h6">Income register</Typography><Records rows={giving} columns={columns} /><Typography variant="h6">Expense register</Typography><Records rows={expenses} columns={expenseColumns} /><Typography variant="body2">Cash totals include completed giving and paid expenses only. Pending payments, pledges and issued invoices are not received cash. This is a cash-movement report, not a bank balance or audited accounts.</Typography></>}
    {documentType === 'tithes' && <Records rows={giving.filter((g: any) => /^tithes?$/i.test(String(g.purpose || '').trim()))} columns={columns} />}
    {documentType === 'expenses' && <Records rows={expenses} columns={expenseColumns} />}
    {documentType === 'receipt' && (selected ? <Box sx={{ border: '1px solid #ddd', p: 3 }}><Typography fontWeight={700}>Receipt {selected.id}</Typography><Typography sx={{ mt: 2 }}>Received from: {selected.donorName || 'Anonymous'}</Typography><Typography>Amount: {money(selected.amount, selected.currency)}</Typography><Typography>Purpose: {selected.purpose}</Typography><Typography>Collection time: {stamp(selected.receivedAt)}</Typography><Typography>Recorded at: {stamp(selected.createdAt)}</Typography><Typography>Method: {selected.paymentMethod}</Typography><Typography sx={{ overflowWrap: 'anywhere' }}>Reference: {selected.reference}</Typography><Typography sx={{ mt: 2 }}>Payment status: Completed</Typography></Box> : <Alert severity="info">Select a completed gift to preview its receipt. Pending and failed gifts cannot receive a paid receipt.</Alert>)}
    {documentType === 'invoice' && (selected ? <Box sx={{ border: '1px solid #ddd', p: 3 }}><Typography fontWeight={700} sx={{ overflowWrap: 'anywhere' }}>Invoice {selected.id}</Typography><Typography sx={{ mt: 2 }}>Bill to: {selected.recipient}</Typography><Typography sx={{ whiteSpace: 'pre-wrap' }}>{selected.description}</Typography><Typography>Amount due: {money(selected.amount, selected.currency)}</Typography><Typography>Issued: {stamp(selected.issueAt)}</Typography><Typography>Due: {stamp(selected.dueAt)}</Typography><Typography>Status: {selected.status}</Typography><Typography variant="body2" sx={{ mt: 2 }}>This church invoice is separate from the church's platform subscription. Marking it paid does not create a giving record.</Typography></Box> : <Alert severity="info">Select an invoice from this date range, or create one below.</Alert>)}
    {documentType === 'budgets' && <><Alert severity="info">All current budget lines are a snapshot, not filtered by the collection date range. Budget amounts use GHS, as in the existing budget module.</Alert><Records rows={data?.budgets || []} columns={[{ title: 'Fiscal year', value: r => r.fiscalYear }, { title: 'Category', value: r => r.category }, { title: 'Allocated (GHS)', value: r => money(r.allocated) }, { title: 'Spent (GHS)', value: r => money(r.spent) }, { title: 'Remaining (GHS)', value: r => money(Number(r.allocated) - Number(r.spent)) }]} /></>}
    {documentType === 'pledges' && <><Alert severity="info">All current pledges are a snapshot. Promises are not counted as collected income.</Alert><Records rows={(data?.pledges || []).filter(inCurrency)} columns={[{ title: 'Member', value: r => r.memberName }, { title: 'Purpose', value: r => r.purpose }, { title: 'Pledged', value: r => money(r.amountPledged, r.currency) }, { title: 'Paid', value: r => money(r.amountPaid, r.currency) }, { title: 'Outstanding', value: r => money(Number(r.amountPledged) - Number(r.amountPaid), r.currency) }]} /></>}
  </Stack>;
  return <Stack spacing={3}>
    <Box><Typography variant="h5" fontWeight={800}>Financial reports & documents</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Review a collection period, print receipts and invoices, and plan with a clearly labeled forecast.</Typography></Box>
    <Stack direction={{ xs: 'column', md: 'row' }} gap={2}><TextField type="date" label="From (UTC)" value={draft.from} onChange={e => setDraft(v => ({ ...v, from: e.target.value }))} slotProps={{ inputLabel: { shrink: true } }} /><TextField type="date" label="To (UTC)" value={draft.to} onChange={e => setDraft(v => ({ ...v, to: e.target.value }))} slotProps={{ inputLabel: { shrink: true } }} /><TextField select label="Forecast months" value={draft.horizon} onChange={e => setDraft(v => ({ ...v, horizon: Number(e.target.value) }))} sx={{ minWidth: 170 }}>{[1, 3, 6, 12].map(n => <MenuItem key={n} value={n}>{n} months</MenuItem>)}</TextField><Button variant="contained" onClick={apply} disabled={loading}>Apply range</Button></Stack>
    {error && <Alert severity="error" action={<Button onClick={() => setRevision(v => v + 1)}>Retry</Button>}>{error}</Alert>}
    {loading ? <Box sx={{ textAlign: 'center', p: 4 }}><CircularProgress aria-label="Loading finance documents" /></Box> : data && <>
      <Stack direction={{ xs: 'column', md: 'row' }} gap={2}><TextField select label="Currency" value={currency} onChange={e => { setCurrency(e.target.value); setRecordId(''); }} sx={{ minWidth: 160 }}><MenuItem value="all">All, separately</MenuItem>{currencies.map(c => <MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField><TextField select label="Document" value={documentType} onChange={e => { setDocumentType(e.target.value); setRecordId(''); }} sx={{ flex: 1 }}>{types.map(([v, l]) => <MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField></Stack>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' }, gap: 2 }}>{totals.map((t: any) => <Card variant="outlined" key={t.currency}><CardContent><Typography variant="body2" color="text.secondary">Completed tithes · {t.currency}</Typography><Typography variant="h5" fontWeight={800}>{money(t.tithes, t.currency)}</Typography><Typography variant="body2" color="text.secondary">Income {money(t.income, t.currency)} · Paid expenses {money(t.expenses, t.currency)}</Typography></CardContent></Card>)}</Box>
      {['receipt', 'invoice'].includes(documentType) && <TextField select label={documentType === 'receipt' ? 'Completed giving record' : 'Church invoice'} value={recordId} onChange={e => setRecordId(e.target.value)}><MenuItem value="">Select a record</MenuItem>{individualRows.map((r: any) => <MenuItem key={r.id} value={String(r.id)} sx={{ whiteSpace: 'normal' }}>{r.recipient || r.donorName || 'Anonymous'} · {money(r.amount, r.currency)} · {stamp(r.receivedAt || r.issueAt)} · {r.id}</MenuItem>)}</TextField>}
      <Button variant="contained" disabled={['receipt', 'invoice'].includes(documentType) && !selected} onClick={() => setPrint(true)} sx={{ alignSelf: 'flex-start' }}>Print / Save PDF</Button>
      <Card variant="outlined"><CardContent>{documentBody}</CardContent></Card>
      {documentType === 'invoice' && <><Typography variant="h6" fontWeight={700}>Manage church invoices</Typography><CrudTable columns={[{ key: 'recipient', label: 'Recipient' }, { key: 'amount', label: 'Amount', render: r => money(r.amount, r.currency) }, { key: 'issueAt', label: 'Issued', render: r => stamp(r.issueAt) }, { key: 'status', label: 'Status' }]} fields={[{ name: 'recipient', label: 'Recipient', required: true }, { name: 'description', label: 'Description', type: 'textarea', required: true }, { name: 'amount', label: 'Amount', type: 'number', required: true }, { name: 'currency', label: 'Currency', defaultValue: 'GHS', required: true }, { name: 'issueAt', label: 'Issue date & time', type: 'datetime' }, { name: 'dueAt', label: 'Due date & time', type: 'datetime' }]} fetchRows={async () => (await api.get('/church/finance/invoices')).data.data} createRow={async b => { const r = await api.post('/church/finance/invoices', b); setRevision(v => v + 1); return r.data; }} rowActions={(r, reload) => <Stack direction="row" gap={1}>{r.status !== 'void' && ['paid', 'void'].filter(s => s !== r.status).map(s => <Button key={s} onClick={async () => { try { await api.patch(`/church/finance/invoices/${encodeURIComponent(r.id)}`, { status: s }); reload(); setRevision(v => v + 1); } catch (e) { setError(problem(e)); } }}>{s === 'paid' ? 'Mark paid' : 'Void'}</Button>)}</Stack>} addLabel="Create invoice" /></>}
    </>}
    {print && <PrintDocument title={types.find(([v]) => v === documentType)?.[1] || 'Financial document'} onClose={() => setPrint(false)}>{documentBody}</PrintDocument>}
  </Stack>;
}
